### ISSUE TITLE
Compilation error on python3.9

### ISSUE THREAD

**Issue by dulfox** [bjornt/pysmbus#3]
When I try to compile on my raspberrypi with python3.9, I get the following error :

Collecting pysmbus
  Downloading pysmbus-**0.1-3**.tar.gz (2.4 kB)
**ERROR: Requested pysmbus from https://files.pythonhosted.org/packages/a1/d8/68240a0e2a9ae5b67a08014d5ba183ac312cc65cfe52eec5e6048d377e6d/pysmbus-0.1-3.tar.gz#sha256=f5158b36aae7f8685fbb52da5ec8a6f242a15d74aa3cfc288ad19e917586c2c9 has different version in metadata: '0.1'**

I have to do : sudo pip install pysmbus **--use-deprecated=legacy-resolver**

This resolver will be deprecated soon.

Could you please update your package to the new packaging rules, please ?

Kind regards.

**Comment by SimpleArt** [comment]
The same error and fix happen for python `3.7` and `3.10`.
